workshop/main/urls.py
from django.urls import path

from workshop.main.views.generic import HomeView, DashboardView
from workshop.main.views.pet_photos import CreatePetPhotoView, like_pet_photo, \
    PetPhotoDetailsView, EditPetPhotoView
from workshop.main.views.pets import CreatePetView, EditPetView, DeletePetView

urlpatterns = (
    path('', HomeView.as_view(), name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('photo/add/', CreatePetPhotoView.as_view(), name='create pet photo'),
    path('photo/details/<int:pk>/', PetPhotoDetailsView.as_view(), name='pet photo details'),
    path('photo/edit/<int:pk>/', EditPetPhotoView.as_view(), name='edit pet photo'),
    path('photo/like/<int:pk>/', like_pet_photo, name='like pet photo'),

    path('pet/add/', CreatePetView.as_view(), name='create pet'),
    path('pet/edit/<int:pk>/', EditPetView.as_view(), name='edit pet'),
    path('pet/delete/<int:pk>/', DeletePetView.as_view(), name='delete pet'),
)

workshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workshop.main.urls')),
    path('accounts/', include('workshop.accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workshop/main/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Pet(models.Model):
    CAT = 'Cat'
    DOG = 'Dog'
    BUNNY = 'Bunny'
    PARROT = 'Parrot'
    FISH = 'Fish'
    OTHER = 'Other'

    TYPES = [(x, x) for x in (CAT, DOG, BUNNY, PARROT, FISH, OTHER)]
    NAME_MAX_LENGTH = 30

    name = models.CharField(
        max_length=NAME_MAX_LENGTH,
    )

    type = models.CharField(
        max_length=max(len(x) for (x, _) in TYPES),
        choices=TYPES
    )

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    @property
    def age(self):
        return datetime.datetime.now().year - self.date_of_birth.year

    class Meta:
        unique_together = ('user', 'name')


class PetPhoto(models.Model):
    photo = models.ImageField()

    description = models.TextField(
        null=True,
        blank=True,
    )

    publication_date = models.DateTimeField(
        auto_now_add=True,
    )

    likes = models.IntegerField(
        default=0,
    )

    tagged_pets = models.ManyToManyField(
        Pet,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

workshop/accounts/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms, get_user_model

from workshop.accounts.models import Profile
from workshop.common.helpers import BootstrapFormMixin
from workshop.main.models import PetPhoto


class CreateProfileForm(BootstrapFormMixin, auth_forms.UserCreationForm):
    first_name = forms.CharField(
        max_length=Profile.FIRST_NAME_MAX_LENGTH,
    )

    last_name = forms.CharField(
        max_length=Profile.LAST_NAME_MAX_LENGTH,
    )

    picture = forms.URLField()

    date_of_birth = forms.DateField()

    description = forms.CharField(
        widget=forms.Textarea,
    )

    email = forms.EmailField()

    gender = forms.ChoiceField(
        choices=Profile.GENDERS
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_control()

    def save(self, commit=True):
        user = super().save(commit=commit)

        profile = Profile(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            picture=self.cleaned_data['picture'],
            date_of_birth=self.cleaned_data['date_of_birth'],
            description=self.cleaned_data['description'],
            email=self.cleaned_data['email'],
            gender=self.cleaned_data['gender'],
            user=user,
        )

        if commit:
            profile.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'picture', 'description')
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter first name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter last name',
                }
            ),
            'picture': forms.TextInput(
                attrs={
                    'placeholder': 'Enter URL',
                }
            ),
        }


class EditProfileForm(BootstrapFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_control()
        self.initial['gender'] = Profile.DO_NOT_SHOW

    class Meta:
        model = Profile
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter first name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter last name',
                }
            ),
            'picture': forms.TextInput(
                attrs={
                    'placeholder': 'Enter URL',
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'Enter email',
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'placeholder': 'Enter description',
                    'rows': 3,
                }
            ),
            'date_of_birth': forms.DateInput(
                attrs={
                    'min': '1920-01-01',
                }
            ),
        }


class DeleteProfileForm(forms.ModelForm):
    def save(self, commit=True):
        pets = list(self.instance.pet_set.all())
        PetPhoto.objects.filter(tagged_pets__in=pets).delete()
        self.instance.delete()

        return self.instance

    class Meta:
        model = Profile
        fields = ()

workshop/main/forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError

from workshop.main.models import Pet
from workshop.common.helpers import BootstrapFormMixin, DisabledFormMixin


class CreatePetForm(BootstrapFormMixin, forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self._init_bootstrap_form_control()

    def save(self, commit=True):
        pet = super().save(commit=False)

        pet.user = self.user
        if commit:
            pet.save()

        return pet

    class Meta:
        model = Pet
        fields = ('name', 'type', 'date_of_birth')
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter pet name',
                }
            ),
        }


class EditPetForm(BootstrapFormMixin, forms.ModelForm):
    MIN_DATE_OF_BIRTH = date(1920, 1, 1)
    MAX_DATE_OF_BIRTH = date.today()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_control()

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data['date_of_birth']
        if date_of_birth < self.MIN_DATE_OF_BIRTH or \
                self.MAX_DATE_OF_BIRTH < date_of_birth:
            raise ValidationError(
                f'Date of birth must be between {self.MIN_DATE_OF_BIRTH} and {self.MAX_DATE_OF_BIRTH}')

        return date_of_birth

    class Meta:
        model = Pet
        exclude = ('user',)


class DeletePetForm(BootstrapFormMixin, DisabledFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_control()
        self._init_disabled_fields()

    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = Pet
        exclude = ('user',)

workshop/main/views.py
from django.shortcuts import render

# Create your views here.

workshop/main/views/generic.py
from django.shortcuts import render, redirect
from django.views import generic as views

from workshop.common.view_mixins import RedirectToDashboard
from workshop.main.models import PetPhoto


class HomeView(RedirectToDashboard, views.TemplateView):
    template_name = 'main/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hide_additional_nav_items'] = True
        return context


class DashboardView(views.ListView):
    model = PetPhoto
    template_name = 'main/dashboard.html'
    context_object_name = 'pet_photos'

workshop/main/views/pet_photos.py
from django.contrib.auth import mixins as auth_mixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic as views

from workshop.main.models import PetPhoto


class PetPhotoDetailsView(auth_mixin.LoginRequiredMixin, views.DetailView):
    model = PetPhoto
    template_name = 'main/photo_details.html'
    context_object_name = 'pet_photo'

    def get_queryset(self):
        return super().get_queryset().prefetch_related('tagged_pets')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['is_owner'] = self.object.user == self.request.user

        return context


class CreatePetPhotoView(auth_mixin.LoginRequiredMixin, views.CreateView):
    model = PetPhoto
    template_name = 'main/photo_create.html'
    fields = ('photo', 'description', 'tagged_pets')

    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EditPetPhotoView(views.UpdateView):
    model = PetPhoto
    template_name = 'main/photo_edit.html'
    fields = ('description',)

    def get_success_url(self):
        return reverse_lazy('pet photo details', kwargs={'pk': self.object.id})


def like_pet_photo(request, pk):
    pet_photo = PetPhoto.objects.get(pk=pk)
    pet_photo.likes += 1
    pet_photo.save()

    return redirect('pet photo details', pk)


def create_pet_photo(request):
    return render(request, 'main/photo_create.html')

workshop/main/views/pets.py
from django.urls import reverse_lazy
from django.views import generic as views

from workshop.main.forms import CreatePetForm, EditPetForm, DeletePetForm


class CreatePetView(views.CreateView):
    template_name = 'main/pet_create.html'
    form_class = CreatePetForm

    success_url = reverse_lazy('dashboard')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class EditPetView(views.UpdateView):
    template_name = 'main/pet_edit.html'
    form_class = EditPetForm


class DeletePetView(views.DeleteView):
    template_name = 'main/pet_delete.html'
    form_class = DeletePetForm

templates/main/401_error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<div class="container mb-5 mt-2">
    <div class="jumbotron">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="position-sticky">
            <h1 class="display-4">401 Unauthorized</h1>
            <p class="lead">You should create a profile to open this page!</p>
            <hr class="my-4">
            <div class="row col-lg-6">

                <!-- Button to show when profile is NOT created -->
                <a href="#" class="btn btn-lg btn-secondary">Create Profile</a>
            </div>
        </div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</body>
</html>

templates/main/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <h1 class='text-center'>
        {% if pet_photos %}
            All Pet Photos
        {% else %}
            No pet photos yet
        {% endif %}
    </h1>

    {% if pet_photos %}
        <div class="container mb-5">
            <div class="row mb-5">
                {% for pet_photo in pet_photos %}
                    <div class="card ml-3 mb-3" style="width: 18rem;">
                        <!-- Image -->
                        <img src="{{ pet_photo.photo.url }}"
                             class="card-img-top" alt="{{ pet_photo.description }}">
                        <div class="card-body">
                            {% for pet in pet_photo.tagged_pets.all %}
                                <h5 class="card-title">{{ pet.name }}{% if pet.date_of_birth %}
                                    {{ pet.age }}
                                {% endif %}</h5>
                            {% endfor %}
                            <!-- First 30 chars from the description -->
                            <p class="card-text">{{ pet_photo.descriptio|truncatechars:30 }}</p>
                            <!-- Button to the Photo Details Page -->
                            <a href="{% url 'pet photo details' pet_photo.id %}" class="btn btn-primary">See details</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class=" row d-flex justify-content-center align-content-center">
            <a href="{% url 'create pet photo' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add
                Photo</a>
        </div>
    {% endif %}

{% endblock %}

templates/main/home_page.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="position-sticky">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="flex-row">
                <a href="{% url 'login user' %}" class="btn btn-lg btn-secondary">Login</a>

                <a href="{% url 'create profile' %}" class="btn btn-lg btn-secondary">Register</a>

            </div>
        </div>
    </div>
{% endblock %}

templates/main/pet_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Form for Adding Pet -->
            <form method="post" action="../accounts/profile_details.html">
                <div class="form-group">
                    <label for="name">Pet Name</label>
                    <input type="text" class="form-control" name="first_name" placeholder="Enter name"
                           id="name"/>
                </div>
                <div class="form-group">
                    <label for="type_animal" class="col-form-label">Type:
                    <select class="form-select">
                        <option value="first">Cat</option>
                        <option value="second">Dog</option>
                        <option value="third">Mouse</option>
                    </select></label>
                </div>
                <div class="form-group">
                    <label for="age">Day of Birth:</label>
                    <input type="date" class="form-control" name="age" placeholder=""
                           id="age"/>
                </div>

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
            <!-- End Form for Adding Pet -->
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

templates/main/pet_create.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Add Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'create pet' %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/main/pet_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Delete Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'delete pet' pet.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-danger mt-2" type="submit">Delete</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/main/pet_edit.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Edit Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk%}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/main/photo_create.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Add a New Pet Photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'create pet photo' %}" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/main/photo_details.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet_photo.photo.url }}"
                 class="w-100 rounded mx-auto d-block" alt="{{ pet_photo.description }}">
        </div>
        <div class="d-inline p-2 w-50">
            {% for pet in pet_photo.tagged_pets.all %}
                <div class="d-flex justify-content-around">
                    <h5><u>Type:</u> {{ pet.type }}</h5>
                    <h5><u>Name:</u> {{ pet.name }}</h5>
                    {% if pet.date_of_birth %}
                        <h5><u>Age:</u> {{ pet.age }}</h5>
                    {% endif %}
                </div>
            {% endfor %}
            <p class="mt-2">{{ pet_photo.description }}</p>
            {% if not is_owner %}
                <a href="{% url 'like pet photo' pet_photo.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            {% endif %}
            <p class="mt-2">Likes: {{ pet_photo.likes }}</p>
            {% if is_owner %}
                <a href="{% url 'edit pet photo' pet_photo.pk %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'delete pet' pet_photo.pk %}" class="btn btn-danger">Delete</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/main/photo_edit.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Edit Pet Photo</h1>
    <img src="{{ object.photo.url}}"
         class="w-50 rounded mx-auto d-block" alt="Photo description">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet photo' object.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/main/profile_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile-page' %}">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" name="first_name" maxlength="30" required
                           placeholder="Enter first name" id="first_name"/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" name="last_name" maxlength="30" required
                           placeholder="Enter last name" id="id_last_name"/>
                </div>
                <div class="form-group">
                    <label for="id_image">Link to Profile Image</label>
                    <input type="url" class="form-control" name="profile_image" required id="id_image"
                    placeholder="Enter URL"/>
                </div>
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>